#!/bin/bash

set -euo pipefail

# ------------------------------------------------------------------------------
# Network
# ------------------------------------------------------------------------------

CARDANO_SOCKET="./devnet-env/socket/node1/sock"
CARDANO_TESTNET_MAGIC="42"

# ------------------------------------------------------------------------------
# Endpoints
# ------------------------------------------------------------------------------

QUERY_API="http://localhost:8081/api/v3"
CARDANO_API="http://localhost:8081/api/v3"
KUBER_API="http://localhost:8081/api/v1"

# ------------------------------------------------------------------------------
# Globals
# ------------------------------------------------------------------------------

WORK_DIR="work"
CONFIG_DIR="dev-local"

TOKEN_NAME="TEST_TOKEN"
POLICY=$(cat "$CONFIG_DIR/policy.plutus")
TOKEN_NAME_HEX=$(printf "%s" "$TOKEN_NAME" | xxd -p | tr -d '\n')
POLICY_HASH=$(cardano-cli latest transaction policyid --script-file "$CONFIG_DIR/policy.plutus")

# NOTE: Ensure these files exist!
WALLET_KEY="devnet-env/utxo-keys/utxo3/utxo.skey"
WALLET_ADDR_FILE="devnet-env/utxo-keys/utxo3/utxo.addr"

# ------------------------------------------------------------------------------
# Derived
# ------------------------------------------------------------------------------

WALLET_ADDR=$(cat $WALLET_ADDR_FILE)

# ------------------------------------------------------------------------------
# Function return registers
# ------------------------------------------------------------------------------

TX_ID=""

# ------------------------------------------------------------------------------
# Utils
# ------------------------------------------------------------------------------

step () {
    local STEP=$1
    echo ""
    echo "------------------------------------------------"
    echo "$STEP"
    echo "------------------------------------------------"
    echo ""
}

print_var () {
    local VAR=$1
    eval "echo \"$VAR: \$$VAR\""
}

run () {
  echo "$*"
  "$@"
}

# ------------------------------------------------------------------------------
# Functions
# ------------------------------------------------------------------------------

print_env () {
    step "Environment"
    print_var "CARDANO_SOCKET"
    print_var "CARDANO_TESTNET_MAGIC"
    print_var "QUERY_API"
    print_var "CARDANO_API"
    print_var "KUBER_API"
    print_var "TOKEN_NAME"
    print_var "TOKEN_NAME_HEX"
    print_var "POLICY"
    print_var "POLICY_HASH"
    print_var "WALLET_KEY"
    print_var "WALLET_ADDR_FILE"
    print_var "WALLET_ADDR"
}

submit_tx () {
    local TEMPLATE=$1

    echo "Create request.json"
    # 1. Inject real Wallet Address into the JSON template
    cat $TEMPLATE \
        | sed "s/WALLET_ADDR/$WALLET_ADDR/g" \
        | sed "s/TOKEN_NAME_HEX/$TOKEN_NAME_HEX/g" \
        | sed "s/TOKEN_NAME/$TOKEN_NAME/g" \
        | sed "s/POLICY_HASH/$POLICY_HASH/g" \
        | awk -v rep="$POLICY" '{ gsub(/POLICY/, rep); print }' \
        > "$WORK_DIR/request.json"

    run cat "$WORK_DIR/request.json"

    echo "Create balanced transaction"
    curl -sfS -X POST -H "Content-Type: application/json" \
         --data @"$WORK_DIR/request.json" \
         $KUBER_API/tx?submit=false > "$WORK_DIR/tx.unsigned"

    echo "Signing..."
    cardano-cli latest transaction sign \
        --tx-body-file "$WORK_DIR/tx.unsigned" \
        --signing-key-file $WALLET_KEY \
        --out-file "$WORK_DIR/tx.signed"

    # 5. Submit
    echo "Submitting..."
    cardano-cli latest transaction submit \
        --testnet-magic $CARDANO_TESTNET_MAGIC \
        --socket-path $CARDANO_SOCKET \
        --tx-file "$WORK_DIR/tx.signed"

    TX_ID=$(cardano-cli latest transaction txid --tx-file "$WORK_DIR/tx.signed" \
                |  jq -r ".txhash")

    print_var "TX_ID"

    echo "Transaction Submitted Successfully!"
}

# ------------------------------------------------------------------------------
# Main
# ------------------------------------------------------------------------------

main () {
    mkdir -p "$WORK_DIR"

    print_env

    step "Mint"
    submit_tx "dev-local/tx-mint.json"

    echo "Waiting 5 seconds for block confirmation..."
    sleep 5

    echo "Workflow Complete!"
}

main
